name: Update Snake Animation

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Snake SVG
        run: node generateSnake.js  # Adjust script name as needed

      - name: Commit and Push Changes
        run: |
          git config --global user.email "0zarifahnaf7@gmail.com"
          git config --global user.name "zarifc573"
          git add .
          git commit -m "Update snake animation"
          git push
